export const containers = [
  {
    id: "1",
    heading: "Design",
    canAddNewCard: true,
    cards: [
      {
        id: "1",
        numberOfIcons: 1,
        comments: 34,
        likes: 14,
        pins: 34,
        description:
          "Old fashioned recipe for preventing allergies and chemical sensitivities",
      },
      {
        id: "2",
        numberOfIcons: 2,
        comments: 23,
        likes: 12,
        pins: 43,
        description: "Home business advertising ideas",
        info: "Successful businesses know the importance of building and maintaining good working. ",
      },
      {
        id: "3",
        imageUrl: "../assets/Design.png",
        numberOfIcons: 3,
        comments: 54,
        likes: 16,
        pins: 33,
        description: "Cosmetic surgery abroad making the right choice",
      },
    ],
  },
  {
    id: "2",
    heading: "Prototip",
    canAddNewCard: false,
    cards: [
      {
        id: "4",
        numberOfIcons: 0,
        comments: 76,
        likes: 45,
        pins: 12,
        description: "Home business advertising ideas",
        info: "Successful businesses know the importance of building and maintaining good working. ",
      },
      {
        id: "5",
        imageUrl: "../assets/Prototip1.png",
        numberOfIcons: 3,
        comments: 76,
        likes: 32,
        pins: 66,
        description: "Unmatched toner cartridge quality 20 less than oem price",
        info: "Why read motivational sayings? For motivation! You might need a bit, if you can use last year’s list of goals this year because it’s as good as new. ",
      },
      {
        id: "6",
        imageUrl: "../assets/Prototip2.png",
        numberOfIcons: 3,
        comments: 54,
        likes: 76,
        pins: 11,
        description: "How to look up",
        info: "Are you considering buying a compatible inkjet cartridge for your printer?",
      },
    ],
  },
  {
    id: "3",
    heading: "Trello",
    canAddNewCard: true,
    cards: [
      {
        id: "7",
        imageUrl: "../assets/Trello.png",
        numberOfIcons: 3,
        comments: 34,
        likes: 23,
        pins: 96,
        description: "Types of paper in catalog printing",
        info: " Branding is no longer simply about visual appeal (or the cherry in the apple pie example, as given in my earlier article).",
      },
      {
        id: "8",
        numberOfIcons: 2,
        comments: 23,
        likes: 12,
        pins: 44,
        description: "There is no competition ",
        info: " This article is floated online with an aim to help you find the best dvd printing solution.",
      },
    ],
  },
  {
    id: "4",
    heading: "Test",
    canAddNewCard: false,
    cards: [
      {
        id: "9",
        numberOfIcons: 3,
        comments: 32,
        likes: 87,
        pins: 31,
        description: "Linux or windows which is it",
        info: "Saving money – is something we would all like.",
      },
      {
        id: "10",
        imageUrl: "../assets/Test.png",
        numberOfIcons: 3,
        comments: 21,
        likes: 34,
        pins: 17,
        description: "Be single minded ",
        info: " Create a list with all possible keywords that fit to your product, service or business field. ",
      },
      {
        id: "11",
        numberOfIcons: 3,
        comments: 55,
        likes: 23,
        pins: 19,
        description: "Linux or windows which is it",
        info: "Saving money – is something we would all like.",
      },
      {
        id: "11",
        numberOfIcons: 2,
        comments: 12,
        likes: 33,
        pins: 66,
        description: "Dna the future of nutrition ",
        info: "   “Why does anyone want a vasectomy reversal?” This is a question I hear any time I tell someone what I do for a living.",
      },
    ],
  },
  {
    id: "5",
    heading: "Final",
    canAddNewCard: false,
    cards: [
      {
        id: "12",
        numberOfIcons: 0,
        comments: 87,
        likes: 54,
        pins: 32,
        description: "At home treatments for beauty on a budget ",
        info: "The holidays bring with them thoughts of carving and serving delicious turkey dinners to your family and friends. Tradition has its fans, but perhaps this year you’d like to try a twist to your turkey recipe.",
      },
      {
        id: "13",
        numberOfIcons: 2,
        comments: 13,
        likes: 11,
        pins: 43,
        description: "Home business advertising ideas ",
        info: "Successful businesses know the importance of building and maintaining good working.",
      },
      {
        id: "14",
        imageUrl: "../assets/Final.png",
        numberOfIcons: 3,
        comments: 21,
        likes: 23,
        pins: 12,
        description: "Tips for choosing the perfect gloss for your lips",
        info: " With MySpace becoming more popular every day, there is the constant need to be different. There are millions of users.",
      },
    ],
  },
];
